### ISSUE TITLE
maxdiff doesn't seem robust to different text encoding settings

### ISSUE THREAD

**Issue by diemoschwarz** [Ableton/maxdevtools#15]
Hi Mattijs,

first try with the very welcome maxdiff, I run into this problem:
```
%python3 ~/src/maxdevtools-ableton/maxdiff/amxd_textconv.py cocavs-image.amxd
Traceback (most recent call last):
  File "/Users/schwarz/src/maxdevtools-ableton/maxdiff/amxd_textconv.py", line 106, in <module>
    main()
  File "/Users/schwarz/src/maxdevtools-ableton/maxdiff/amxd_textconv.py", line 99, in main
    print(result)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2013' in position 150942: ordinal not in range(256)
```
I need to do `setenv PYTHONIOENCODING UTF-8` to make it work. Maybe my setup is weird, but can't the encoding be enforced by the scripts themselves? Best!

**Comment by MattijsKneppers** [comment]
Hi @diemoschwarz , thanks for reporting this. I can't seem to reproduce this. Would you be able to attach a device that demonstrates this issue for you?

**Comment by diemoschwarz** [comment]
of course, here is one: [cocavs-image-imera copy.amxd.zip](https://github.com/Ableton/maxdevtools/files/14511340/cocavs-image-imera.copy.amxd.zip). Most amxds don't give the error, there must be a weird character in some comment.

I remember having to do things like this in other code: `f'File: {file.path}'.encode('utf-8')`

```
%python3 ~/src/maxdevtools-ableton/maxdiff/amxd_textconv.py ./src/cocavs/patches/cocavs-image-imera\ copy.amxd 
Traceback (most recent call last):
  File "/Users/schwarz/src/maxdevtools-ableton/maxdiff/amxd_textconv.py", line 106, in <module>
    main()
  File "/Users/schwarz/src/maxdevtools-ableton/maxdiff/amxd_textconv.py", line 99, in main
    print(result)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u0300' in position 33853: ordinal not in range(256)
```

**Comment by MattijsKneppers** [comment]
Following up: indeed if I set my `PYTHONIOENCODING` variable to `ascii` I get the same error as you do with a device that contains an emoji. By default, `PYTHONIOENCODING` seems to be set to `utf-8`, but as you say, perhaps there is a way to enforce this for the script.

Interestingly, the decoding of the patch file buffer is explicitly [using utf-8](https://github.com/Ableton/maxdevtools/blob/f6791623fe98274321b421744b2bf684b6447375/maxdiff/amxd_textconv.py#L85). I'll investigate further.

**Comment by MattijsKneppers** [comment]
Ok I found the issue, it's actually in the `print` statement, which can't print utf-8 strings if the encoding is set to `ascii`. 

I'll see if there is a proper fix.

**Comment by MattijsKneppers** [comment]
Ok @diemoschwarz I think PR https://github.com/Ableton/maxdevtools/pull/20 should fix this. It would be great if you could confirm this.

**Comment by MattijsKneppers** [comment]
Great, thanks for confirming!

Indeed I haven't yet found a way to integrate textconv scripts with github or sourcetree..
