### ISSUE TITLE
Running audio based tests using Ableton

### ISSUE THREAD

**Issue by allforabit** [Ableton/maxdevtools#26]
Great resource thank you. I'm just wondering if it's possible to automate the generation of audio generation with Ableton for third party developers to aid testing or is this more of an internal capability?

**Comment by MattijsKneppers** [comment]
@allforabit I agree it would be great to have ways to automatically export audio for test Live sets and compare between versions.

At the moment, I'd say your best best is to manually export a test set to an audio file, once for the version of a device that you know works as expected, and once for an updated version. Then you can compare the exports, by ear (e.g. panning one export fully left and the other fully right) or, if the device output is deterministic, by exporting the sum of both exports after inverting the phase of one of them.

Once we have ways to make this process more automatic I hope to add these here.

**Comment by allforabit** [comment]
OK thank you for the info, good to hear that is something that is being thought about 👍
